[platformio]
default_envs = esp32-ideaspark

[env]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags = -Wall -Wextra
lib_deps = bblanchon/ArduinoJson@6.21.5

[env:esp32-oled]
lib_deps =
  ${env.lib_deps}
  olikraus/U8g2@2.36.5

[env:esp32-ideaspark]
build_flags = ${env.build_flags} -DPET_TFT_IDEASPARK=1
lib_deps =
  ${env.lib_deps}
  lovyan03/LovyanGFX@1.2.7

[env:esp32-codey]
extends = env:esp32-ideaspark
build_flags = ${env:esp32-ideaspark.build_flags} -DPET_CODEY=1
